### ISSUE TITLE
Generator last version doesn't work / crash

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#37]
Just try to update deps on the sqflite example and nothing is working anymore.
Here is the stack

```

// **************************************************************************
// BeanGenerator
// **************************************************************************

/*
NoSuchMethodError: Attempted to use type 'WriterInfo' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the WriterInfo constructor and forget the 'new' operator?
Receiver: WriterInfo
Tried calling: WriterInfo("PostBean", "Post", _LinkedHashMap len:5, Instance(length:1) of '_GrowableList', _LinkedHashMap len:0, _LinkedHashMap len:0, Instance(length:0) of '_GrowableList')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:216:27)
#2      BeanGenerator.generateForAnnotatedElement (package:jaguar_orm_gen/src/hook/hook.dart:38:42)
<asynchronous suspension>
#3      GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:42:28)
<asynchronous suspension>
#4      _generate (package:source_gen/src/builder.dart:213:35)
<asynchronous suspension>
#5      _Builder._generateForLibrary (package:source_gen/src/builder.dart:74:15)
<asynchronous suspension>
#6      _Builder.build (package:source_gen/src/builder.dart:68:11)
<asynchronous suspension>
#7      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:43:21)
<asynchronous suspension>
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:343)
#10     Future.wait (dart:async/future.dart:385)
#11     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:49:36)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     runZoned (dart:async/zone.dart:1490)
#15     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#16     runBuilder (package:build/src/generate/run_builder.dart:49:9)
<asynchronous suspension>
#17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:424:15)
#18     _NoOpBuilderActionTracker.track (package:build_runner_core/src/generate/performance_tracker.dart:246:73)
#19     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:423:19)
<asynchronous suspension>
#20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:349:38)
#21     MappedIterator.moveNext (dart:_internal/iterable.dart:392)
#22     Future.wait (dart:async/future.dart:385)
#23     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:348:36)
<asynchronous suspension>
#24     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:296:32)
<asynchronous suspension>
#25     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:140:15)
#26     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:292:33)
<asynchronous suspension>
#27     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
<asynchronous suspension>
#28     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:260:26)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1126)
#30     _CustomZone.run (dart:async/zone.dart:1023)
#31     runZoned (dart:async/zone.dart:1490)
#32     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:255:5)
#33     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:185:24)
<asynchronous suspension>
#34     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:89:30)
#35     BuildRunner.run (package:build_runner_core/src/generate/build_runner.dart:23:14)
#36     build (package:build_runner/src/generate/build.dart:98:30)
<asynchronous suspension>
#37     BuildCommand.run (package:build_runner/src/entrypoint/build.dart:28:24)
<asynchronous suspension>
#38     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#39     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#40     new Future.sync (dart:async/future.dart:222)
#41     CommandRunner.run (package:args/command_runner.dart:109:11)
#42     run (package:build_runner/src/entrypoint/run.dart:22:31)
<asynchronous suspension>
#43     main (file:///Users/jaumard/StudioProjects/sqfliteJaguarExample/.dart_tool/build/entrypoint/build.dart:10:22)
<asynchronous suspension>
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
*/
```

**Comment by jaumard** [comment]
Is there any breaking changes and I need to update anything else ?

**Comment by tejainece** [comment]
Hey,

Sorry, tried to upgrade orm to Dart2 65. Flutter still uses 58. Will switch it back.

**Comment by Pepperychef** [comment]
there is a solution to this problem?... trying to test jaguar_orm_gen: ^2.1.1 from dartlang and i'm having the same issue.

**Comment by jaumard** [comment]
@tejainece is this just because you build it with 65 ? or is this dependency written somewhere ? Wasn't able to find it ^^ (sorry if it's a dumb question, still very new to dart)

**Comment by tejainece** [comment]
In Dart2, you can call constructors like functions. I replaced some such construction in calls out of practice.This has been allowed since Dart2 in preview mode. From 64 onwards, preview mode is the default mode.

Now, I am stuck whether to go back or wait for Flutter to move forward.

**Comment by tejainece** [comment]
Will fix this tomorrow or day after

**Comment by tejainece** [comment]
There are lot of local changes on my side, so don't sent pull request until i push. Some new features coming up.

**Comment by jaumard** [comment]
You mean don't put the `new` keyword ? I already don't put them on my flutter code to avoid useless code ^^ but still have the crash, that's weird. Maybe flutter active the preview mode by default when it run but not when you generate code. Maybe the solution is just to put into the readme the command line to have the preview mode enable when generate code. Like this no need to revert until flutter upgrade dart sdk. I mean for me it's acceptable :)

**Comment by jaumard** [comment]
I tried to enable the preview mode but I guess it's not enough, still have problems:
```
DART_VM_OPTIONS=--preview-dart-2 flutter packages pub run build_runner build --delete-conflicting-outputs
Unable to spawn isolate: file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/builder/post_process_builder.dart:9:1: Error: 'PostProcessBuildStep' is imported from both 'package:build/src/builder/post_process_build_step.dart' and 'package:build_runner/src/builder/post_process_build_step.dart'.
import 'post_process_build_step.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/package_graph/apply_builders.dart:13:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import '../builder/post_process_builder.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/generate/phase.dart:10:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import '../builder/post_process_builder.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/generate/build_impl.dart:22:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import '../builder/post_process_builder.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/builder/run_post_process_builder.dart:14:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import 'post_process_builder.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/performance_tracking/performance_tracking_resolvers.dart:11:7: Error: The non-abstract class 'PerformanceTrackingResolvers' is missing implementations for these members:
  'reset'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class PerformanceTrackingResolvers implements Resolvers {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/asset_graph/graph.dart:351:40: Error: The getter 'inputExtensions' isn't defined for the class 'invalid-type'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'inputExtensions'.
      inputExtensions = action.builder.inputExtensions;
                                       ^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/generate/build_impl.dart:498:11: Error: Method not found: 'runPostProcessBuilder'.
    await runPostProcessBuilder(builder, input, wrappedReader, wrappedWriter,
          ^^^^^^^^^^^^^^^^^^^^^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/builder/run_post_process_builder.dart:27:25: Error: Method not found: 'PostProcessBuildStep'.
    var buildStep = new PostProcessBuildStep(
                        ^^^^^^^^^^^^^^^^^^^^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/builder/run_post_process_builder.dart:30:21: Error: The method 'build' isn't defined for the class 'invalid-type'.
Try correcting the name to the name of an existing method, or defining a method named 'build'.
      await builder.build(buildStep);
                    ^
pub finished with exit code 1
```
Maybe because you use both relative and package import for the same file, I had the problem on my app with this and replace every import with package instead of relative, may work here too

**Comment by jaumard** [comment]
Or maybe is just because you use build_runner 0.9.0 where flutter can't use it `Because kiwi_mobile depends on build_runner >=0.9.0 which requires SDK version >=2.0.0-dev.61 <3.0.0, version solving failed.
pub get failed (1)`

`0.8.3` max :/

**Comment by tejainece** [comment]
Yes. That too. For 65+, you need build_runner 0.9.0. I was hoping Flutter would move to 65. They are very slow.

**Comment by jaumard** [comment]
yeah the preview version didn't move since 50 days or something, and as they don't have any roadmap we're totally blind on that... annoying

**Comment by tejainece** [comment]
So, I have fixed. `jaguar_orm`: `2.1.15`. `jaguar_orm_gen`: `2.1.8`. Please upgrade and test it and let me know.

It also contains new features like relations without associations, etc.

Pull requests are welcome.

**Comment by tejainece** [comment]
> Pull requests are welcome.

I mean now. Pushed all my local changes.

**Comment by tejainece** [comment]
Also added some unit tests.

**Comment by jaumard** [comment]
Yeah I need to more understand how jaguar orm / gen before being able to make PR ^^ but I will if I can for sure :) 
Just tested those new versions but still have the `new` error and when I enable preview I have: 
```
DART_VM_OPTIONS=--preview-dart-2 flutter packages pub run build_runner build --delete-conflicting-outputs
Unable to spawn isolate: file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/builder/post_process_builder.dart:9:1: Error: 'PostProcessBuildStep' is imported from both 'package:build/src/builder/post_process_build_step.dart' and 'package:build_runner/src/builder/post_process_build_step.dart'.
import 'post_process_build_step.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/package_graph/apply_builders.dart:13:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import '../builder/post_process_builder.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/generate/phase.dart:10:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import '../builder/post_process_builder.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/generate/build_impl.dart:22:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import '../builder/post_process_builder.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/builder/run_post_process_builder.dart:14:1: Error: 'PostProcessBuilder' is imported from both 'package:build/src/builder/post_process_builder.dart' and 'package:build_runner/src/builder/post_process_builder.dart'.
import 'post_process_builder.dart';
^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/performance_tracking/performance_tracking_resolvers.dart:11:7: Error: The non-abstract class 'PerformanceTrackingResolvers' is missing implementations for these members:
  'reset'.
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class PerformanceTrackingResolvers implements Resolvers {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/asset_graph/graph.dart:351:40: Error: The getter 'inputExtensions' isn't defined for the class 'invalid-type'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'inputExtensions'.
      inputExtensions = action.builder.inputExtensions;
                                       ^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/generate/build_impl.dart:498:11: Error: Method not found: 'runPostProcessBuilder'.
    await runPostProcessBuilder(builder, input, wrappedReader, wrappedWriter,
          ^^^^^^^^^^^^^^^^^^^^^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/builder/run_post_process_builder.dart:27:25: Error: Method not found: 'PostProcessBuildStep'.
    var buildStep = new PostProcessBuildStep(
                        ^^^^^^^^^^^^^^^^^^^^
file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/build_runner-0.8.3/lib/src/builder/run_post_process_builder.dart:30:21: Error: The method 'build' isn't defined for the class 'invalid-type'.
Try correcting the name to the name of an existing method, or defining a method named 'build'.
      await builder.build(buildStep);
                    ^
pub finished with exit code 1
```
I put back all missing `new` to be able to generate but still one problem during generation: 
```

/*
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ParsedBean._getModel.<anonymous closure> (package:jaguar_orm_gen/src/parser/parser.dart:201:68)
#2      Object&ListMixin.firstWhere (dart:collection/list.dart:142)
#3      ParsedBean._getModel (package:jaguar_orm_gen/src/parser/parser.dart:201:10)
#4      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:33:5)
#5      ParsedBean.parseRelation (package:jaguar_orm_gen/src/parser/parser.dart:335:62)
#6      ParsedBean._relation (package:jaguar_orm_gen/src/parser/parser.dart:319:5)
#7      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:282:14)
#8      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:35:5)
#9      BeanGenerator.generateForAnnotatedElement (package:jaguar_orm_gen/src/hook/hook.dart:38:55)
<asynchronous suspension>
#10     GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:42:28)
<asynchronous suspension>
#11     _generate (package:source_gen/src/builder.dart:213:35)
<asynchronous suspension>
#12     _Builder._generateForLibrary (package:source_gen/src/builder.dart:74:15)
<asynchronous suspension>
#13     _Builder.build (package:source_gen/src/builder.dart:68:11)
<asynchronous suspension>
#14     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:43:21)
<asynchronous suspension>
#15     MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#16     ListIterator.moveNext (dart:_internal/iterable.dart:343)
#17     Future.wait (dart:async/future.dart:385)
#18     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:49:36)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1490)
#22     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#23     runBuilder (package:build/src/generate/run_builder.dart:49:9)
<asynchronous suspension>
#24     _SingleBuild._runForInput.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:417:15)
#25     _NoOpBuilderActionTracker.track (package:build_runner/src/generate/performance_tracker.dart:246:73)
#26     _SingleBuild._runForInput (package:build_runner/src/generate/build_impl.dart:416:19)
<asynchronous suspension>
#27     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:348:38)
#28     MappedIterator.moveNext (dart:_internal/iterable.dart:392)
#29     Future.wait (dart:async/future.dart:385)
#30     _SingleBuild._runBuilder (package:build_runner/src/generate/build_impl.dart:347:36)
<asynchronous suspension>
#31     _SingleBuild._runPhases.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:298:32)
<asynchronous suspension>
#32     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner/src/generate/performance_tracker.dart:140:15)
#33     _SingleBuild._runPhases (package:build_runner/src/generate/build_impl.dart:294:33)
<asynchronous suspension>
#34     logTimedAsync (package:build_runner/src/logging/logging.dart:25:30)
<asynchronous suspension>
#35     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:262:26)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1126)
#37     _CustomZone.run (dart:async/zone.dart:1023)
#38     runZoned (dart:async/zone.dart:1490)
#39     _SingleBuild._safeBuild (package:build_runner/src/generate/build_impl.dart:260:5)
#40     _SingleBuild.run (package:build_runner/src/generate/build_impl.dart:204:24)
<asynchronous suspension>
#41     BuildImpl.run (package:build_runner/src/generate/build_impl.dart:149:30)
#42     BuildImpl.create (package:build_runner/src/generate/build_impl.dart:156:37)
<asynchronous suspension>
#43     singleBuild (package:build_runner/src/generate/build_impl.dart:108:33)
<asynchronous suspension>
#44     build (package:build_runner/src/generate/build_impl.dart:97:22)
<asynchronous suspension>
#45     build (package:build_runner/src/generate/build.dart:69:5)
#46     _BuildCommand.run (package:build_runner/src/entrypoint/options.dart:329:24)
<asynchronous suspension>
#47     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#48     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#49     new Future.sync (dart:async/future.dart:222)
#50     CommandRunner.run (package:args/command_runner.dart:109:11)
#51     run (package:build_runner/src/entrypoint/run.dart:22:31)
<asynchronous suspension>
#52     main (file:///Users/jaumard/StudioProjects/kiwi_mobile/.dart_tool/build/entrypoint/build.dart:10:22)
<asynchronous suspension>
#53     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

*/
```
Same problem when I test on the example https://github.com/jaguar-orm/sqflite many to many it failing 
I'll try to search a bit what's going on

**Comment by tejainece** [comment]
Could you send pull request with all the `new` that you have added?

**Comment by jaumard** [comment]
Done :)

**Comment by tejainece** [comment]
Opps. Sorry man. Forgot to publish jaguar_orm_gen 2.1.15. Can you try now?

**Comment by tejainece** [comment]
Also published your changes as `jaguar_orm_gen` `2.1.16`.

**Comment by jaumard** [comment]
I test with the package locally so it doesn't matter if you release or not :) 
On the example, the many to many is still broken with:
```
/*
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ParsedBean._parseFields.<anonymous closure> (package:jaguar_orm_gen/src/parser/parser.dart:265:69)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:439)
#3      Iterable.length (dart:core/iterable.dart:427)
#4      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:266:14)
#5      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:35:5)
#6      ParsedBean.parseRelation (package:jaguar_orm_gen/src/parser/parser.dart:360:63)
#7      ParsedBean._relation (package:jaguar_orm_gen/src/parser/parser.dart:319:5)
#8      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:282:14)
#9      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:35:5)
#10     BeanGenerator.generateForAnnotatedElement (package:jaguar_orm_gen/src/hook/hook.dart:38:55)
<asynchronous suspension>
#11     GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:42:28)
<asynchronous suspension>
#12     _generate (package:source_gen/src/builder.dart:213:35)
<asynchronous suspension>
#13     _Builder._generateForLibrary (package:source_gen/src/builder.dart:74:15)
<asynchronous suspension>
#14     _Builder.build (package:source_gen/src/builder.dart:68:11)
<asynchronous suspension>
#15     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:43:21)
<asynchronous suspension>
#16     MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#17     ListIterator.moveNext (dart:_internal/iterable.dart:343)
#18     Future.wait (dart:async/future.dart:385)
#19     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:49:36)
#20     _rootRun (dart:async/zone.dart:1126)
#21     _CustomZone.run (dart:async/zone.dart:1023)
#22     runZoned (dart:async/zone.dart:1490)
#23     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#24     runBuilder (package:build/src/generate/run_builder.dart:49:9)
<asynchronous suspension>
#25     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:424:15)
#26     _NoOpBuilderActionTracker.track (package:build_runner_core/src/generate/performance_tracker.dart:246:73)
#27     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:423:19)
<asynchronous suspension>
#28     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:349:38)
#29     MappedIterator.moveNext (dart:_internal/iterable.dart:392)
#30     Future.wait (dart:async/future.dart:385)
#31     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:348:36)
<asynchronous suspension>
#32     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:296:32)
<asynchronous suspension>
#33     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:140:15)
#34     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:292:33)
<asynchronous suspension>
#35     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
<asynchronous suspension>
#36     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:260:26)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1126)
#38     _CustomZone.run (dart:async/zone.dart:1023)
#39     runZoned (dart:async/zone.dart:1490)
#40     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:255:5)
#41     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:185:24)
<asynchronous suspension>
#42     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:89:30)
#43     BuildRunner.run (package:build_runner_core/src/generate/build_runner.dart:23:14)
#44     build (package:build_runner/src/generate/build.dart:98:30)
<asynchronous suspension>
#45     BuildCommand.run (package:build_runner/src/entrypoint/build.dart:28:24)
<asynchronous suspension>
#46     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#47     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#48     new Future.sync (dart:async/future.dart:222)
#49     CommandRunner.run (package:args/command_runner.dart:109:11)
#50     run (package:build_runner/src/entrypoint/run.dart:22:31)
<asynchronous suspension>
#51     main (file:///Users/jaumard/StudioProjects/sqfliteJaguarExample/.dart_tool/build/entrypoint/build.dart:10:22)
<asynchronous suspension>
#52     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

*/

```
other example look ok (didn't run them but at least files are gen correctly)

**Comment by tejainece** [comment]
Can I see the bean spec for this many to many example?

**Comment by jaumard** [comment]
Do you mean this https://github.com/jaguar-orm/sqflite/tree/master/lib/many_to_many ? That's the one I test

**Comment by tejainece** [comment]
Alright testing it.

**Comment by tejainece** [comment]
WIP: Patched some of https://github.com/jaguar-orm/sqflite if you want to try with recent code.

Still untested. Testing it.

**Comment by tejainece** [comment]
There have been some minor breaking changes in 2.1.15. Upgraded sqflite example to match them. Now, all generations work and there are no error. Will test it.

https://github.com/jaguar-orm/sqflite/commit/3b0a336e9c88dc1f5297660b48e423538f79c1ee

**Comment by tejainece** [comment]
Tested them. All seem to function like before.

Let me know if I can close this issue.

**Comment by jaumard** [comment]
Look good to me :) I'll open a new issue if needed, the generation work so let's close this one :)
Thanks for the quick fix !
